### ISSUE TITLE
RDS Rule 19-7 Cases

### ISSUE THREAD

**Issue by weilixu** [pnnl/ruleset-checking-tool#1119]
[Rule 19-7](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-7.md) listed out 10 cases and each correspondent to a rule outcome.

After going through the logics I realized one condition, 'modeled_baseline_total_zone_min_OA_CFM == modeled_proposed_total_zone_min_OA_CFM', could be missing from the 10 cases.

So in the case that `!OA_CFM_schedule_match and modeled_baseline_total_zone_min_OA_CFM == modeled_proposed_total_zone_min_OA_CFM`, does it result in `FAIL` or `UNDETERMINED`? What message shall we display in that case?

**Comment by claperle** [comment]
@weilixu Isn't this covered by OA_CFM_schedule_match ==  TRUE? I think I will need to talk through this one on the call on Thursday to better understand the issue.

**Comment by weilixu** [comment]
> vered by OA_CFM_schedule_match == TRUE? I think I will need to talk through this one on the call on Thursday to better understand the issue.

Hi Christina,

Thanks for checking this issue! Below is my understanding:

The `OA_CFM_schedule_match` is `TRUE`  when every hour value of `aggregated_min_OA_schedule_across_zones_b` equal to the ones in `aggregated_min_OA_schedule_across_zone_p` ([description](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-7.md?plain=1#L70-L72))

The `modeled_baseline_total_zone_min_OA_CFM == modeled_proposed_total_zone_min_OA_CFM` is different, it is sum of the `aggregated_min_OA_schedule_across_zones_b` = sum of the `aggregated_min_OA_schedule_across_zone_p` ([description](https://github.com/pnnl/ruleset-checking-tool/blob/develop/docs/section19/Rule19-7.md?plain=1#L74-L75))

In another words,
`OA_CFM_schedule_match = TRUE` guarantees the result: `modeled_baseline_total_zone_min_OA_CFM == modeled_proposed_total_zone_min_OA_CFM`

But `modeled_baseline_total_zone_min_OA_CFM == modeled_proposed_total_zone_min_OA_CFM` does not guarantee `OA_CFM_schedule_match = TRUE`

I am out of office on Thursday. I will see if I can call in to explain further.

**Comment by claperle** [comment]
Hi @weilixu ,

No problem!

So this would be for the scenario where OA_CFM_schedule_match  = FALSE and modeled_baseline_total_zone_min_OA_CFM == modeled_proposed_total_zone_min_OA_CFM. I think this should be a fail because we would expect the schedules to also match not just the total OA CFM.  Would like to get others to weigh-in.

Christina

**Comment by weilixu** [comment]
I am good with a Fail outcome. @claperle

**Comment by claperle** [comment]
@weilixu okay, sounds good. Can you include a note that "Fail because the outdoor air schedules do not appear to match between the baseline and proposed". I doubt this will come up often since it seems unlikely that OA_CFM_schedule_match == FALSE and modeled_baseline_total_zone_min_OA_CFM == modeled_proposed_total_zone_min_OA_CFM == TRUE
