### ISSUE TITLE
Rule 19-3 Applicability

### ISSUE THREAD

**Issue by JacksonJ-KC** [pnnl/ruleset-checking-tool#1455]
> Weather conditions used in sizing runs to determine baseline equipment capacities shall be based ~~either~~ on design days developed using 99.6% heating design temperatures and 1% dry-bulb and 1% wet-bulb cooling design temperatures.

We are currently returning NOT_APPLICABLE when either the cooling design day type does not equal 1% OR the heating design day type does not equal 99.6%. I'm struggling to understand this because it seems like we are discovering that something is incorrect but we are returning NOT_APPLICABLE.

**Comment by claperle** [comment]
@JacksonJ-KC We discussed this one earlier today 8/6/202 and for some reason the RDS got changed after it was approved and merged. There are no circumstances where this would not be applicable which violates the requirements in the standard requiring that each rule evaluated for applicability only have both an undetermined and not applicable outcome. Since this rule is always applicable does that mean that we should remove it from the list of rules? That doesn't seem to make sense since we want to flag this for the reviewer to conduct a manual check.
